### PR TITLE
Fix #270 Use new idler status api to check pod state

### LINKED ISSUE #270: Deprecate idler.IsIdle method in favour of the new status api
Proxy uses `! idler.IsIdle()` to check if pods are `running` but that is wrong as `IsIdle` can return `false` if  pods are just `starting` or `terminating`.  Hence lets use the new api in idler `status` to check if the Pods are actually running.

### PR DESCRIPTION
**Pull request by sthaha**
Proxy uses `!idler.IsIdle()` to check if pods are running but that is
wrong as IsIdle can return `false` if pods are just `starting` or
`terminating`. Hence lets use the new api in idler status to check if the
Pods are actually running.

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @sthaha for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by alien-ike** [comment]
Hey @sthaha! It seems you tried to trigger `/ok-without-tests` command, but this will not have any effect due to insufficient permission. You have to be admin or requested reviewer or pull request approver, but not pull request creator for this command to take an effect.

File: internal/clients/idler.go [hunk 1]
```diff
@@ -32,10 +41,28 @@ type clusterView struct {
...
+type statusResponse struct {
+	Data   *jenkinsInfo    `json:"data,omitempty"`
+	Errors []responseError `json:"errors,omitempty"`
+}
+
 // IdlerService provides methods to talk to the idler client
 type IdlerService interface {
-	IsIdle(tenant string, openShiftAPIURL string) (bool, error)
 	UnIdle(tenant string, openShiftAPIURL string) (int, error)
+	State(tenant string, openShiftAPIURL string) (podState, error)
```
Comment (kishansagathiya) [inline internal/clients/idler.go]: Let's keep this consistent with idler APIs. I think there it is `Status`, isn't it?

File: internal/clients/idler.go [hunk 2]
```diff
@@ -51,45 +78,52 @@ func NewIdler(url string) IdlerService {
 	}
 }
 
-// IsIdle returns true if the Jenkins instance for the specified tenant is idled, false otherwise.
-func (i *idler) IsIdle(tenant string, openShiftAPIURL string) (bool, error) {
+// State returns the state of Jenkins instance for the specified tenant
+func (i *idler) State(tenant string, openShiftAPIURL string) (podState, error) {
```
Comment (kishansagathiya) [inline internal/clients/idler.go]: What's the incentive behind using podState instead of string?

File: internal/clients/idler.go [hunk 3]
```diff
@@ -20,10 +21,18 @@ const (
...
-type status struct {
-	IsIdle bool `json:"is_idle"`
-}
+type podState string
+
+const (
+	// UnknownState used when the state isn't known, along with err
+	UnknownState podState = ""
+	// Running represents a running pod
+	Running = "running"
```
Comment (kishansagathiya) [inline internal/clients/idler.go]: Why is `running` not a podState? Can I use podState and string interchangeably?

File: internal/clients/idler.go (hunk 1 above)
Comment (sthaha) [reply internal/clients/idler.go]: yes, but status is meant to return the entire datastructure related to status which could include many attributes not just the state of a pod.

File: internal/clients/idler.go [hunk 4]
```diff
@@ -51,45 +78,52 @@ func NewIdler(url string) IdlerService {
...
+		return UnknownState, err
 	}
 
-	log.Debugf("Jenkins is idle (%t) in %s", s.IsIdle, namespace)
+	if len(sr.Errors) != 0 {
+		return UnknownState, sr.Errors[0]
 
-	return s.IsIdle, nil
+	}
+
```
Comment (kishansagathiya) [inline internal/clients/idler.go]: Let's put a log here?

File: internal/clients/idler.go (hunk 2 above)
Comment (sthaha) [reply internal/clients/idler.go]: It is a string but type aliased as podState so that golang can type check it e.g.
the code below produces error. 

```go
package main

type Color string

const (
	Red Color = "red"
)

type Name string

const (
	Foobar Name = "foobar"
)

func main() {
	var x Color = Foobar // ERROR
}

```

File: internal/clients/idler.go (hunk 3 above)
Comment (sthaha) [reply internal/clients/idler.go]: Running is a `podState` because the const started with declaring the first const `UnknownState` as a `podState`

File: internal/clients/idler.go (hunk 4 above)
Comment (sthaha) [reply internal/clients/idler.go]: ack .. will submit a correction

**Comment by kishansagathiya** [comment]
`/ok-without-tests`

**Comment by alien-ike** [comment]
Hey @sthaha! It seems you tried to trigger `/ok-without-tests` command, but this will not have any effect due to insufficient permission. You have to be admin or requested reviewer or pull request approver, but not pull request creator for this command to take an effect.
