### PR TITLE
Issue #171 Fixed linting issues, Added `lint` in the `all` target

### LINKED ISSUE #171: Fix linting issues

### PR DESCRIPTION
**Pull request by kishansagathiya**
I would need help with what is remaining.
```
internal/proxy/proxy.go:32:2: exported const GHHeader should have comment (or a comment on this block) or be unexported
internal/router/router.go:8:1: exported function CreateAPIRouter should have comment or be unexported
internal/router/router_test.go:48:2: var mockedProxyApi should be mockedProxyAPI
internal/testutils/common.go:24:1: exported function MockRedirect should have comment or be unexported
internal/testutils/common.go:426:1: exported function GetGHData should have comment or be unexported
internal/testutils/common.go:621:1: exported function OpenShiftIdle should have comment or be unexported
internal/testutils/common.go:632:1: exported function OpenShiftDataRoute should have comment or be unexported
internal/util/osio_token.go:34:6: exported type Result should have comment or be unexported
internal/util/osio_token.go:38:6: exported type TokenResult should have comment or be unexported
internal/util/osio_token.go:43:6: exported type Token should have comment or be unexported

```

Doubt: main.go createAPIRouter() creates proxy API and router for it. What does createProxyRouter do then?

Fixes #171 and #190

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -26,7 +26,8 @@ __check_defined = \
     $(if $(value $1),, \
       $(error Undefined $1$(if $2, ($2))))
 
-all: tools build test fmtcheck vet validate_commits image ## Compiles fabric8-jenkins-proxy and runs format and style checks
+.PHONY: all
+all: tools build test fmtcheck vet validate_commits image lint ## Compiles fabric8-jenkins-proxy and runs format and style checks
```
Comment (hferentschik) [inline Makefile]: Could you please move the `lint` target after vet. As it stands now it comes too late. Really once the image builds you want to have completed all checks

File: cmd/osio/cmd/root.go [hunk 2]
```diff
@@ -21,7 +23,7 @@ func init() {
 		Short: "osio is a helper tool for OpenShift.io.",
 	}
 
-	RootCmd.PersistentFlags().StringVarP(&targetEnv, "target", "t", "stage", "Target environment OpenShift.io stage vs prod.")
+	RootCmd.PersistentFlags().StringVarP(&targetEnv, "target", "t", "stage", "target environment OpenShift.io stage vs prod")
```
Comment (hferentschik) [inline cmd/osio/cmd/root.go]: Why would you change this? This is not an error message. Did the linter complain about that? This is the Viper help.

File: internal/configuration/env_config.go [hunk 3]
```diff
@@ -103,39 +105,39 @@ func (c *EnvConfig) GetPostgresPort() int {
...
+// GetPostgresPassword returns the postgres password as set via default, config file, or environment variable.
 func (c *EnvConfig) GetPostgresPassword() string {
 	callPtr, _, _, _ := runtime.Caller(0)
 	value := getConfigValueFromEnv(util.NameOfFunction(callPtr))
 
 	return value
 }
 
-// GetPostgresSSLMode returns the postgres sslmode as set via default, config file, or environment variable
+// GetPostgresSSLMode returns the postgres SSL mode as set via default, config file, or environment variable.
```
Comment (hferentschik) [inline internal/configuration/env_config.go]: it depends what is meant here. The flag is indeed `sslmode` in Postgres. No need to change imo.

File: internal/configuration/env_config.go [hunk 4]
```diff
@@ -164,63 +166,63 @@ func (c *EnvConfig) GetPostgresConnectionMaxOpen() int {
...
+// GetAuthToken returns the Auth token as set via default, config file, or environment variable.
 func (c *EnvConfig) GetAuthToken() string {
 	callPtr, _, _, _ := runtime.Caller(0)
 	value := getConfigValueFromEnv(util.NameOfFunction(callPtr))
 
 	return value
 }
 
-// GetRedirectURL returns the redirect url to be passed to Auth as set via default, config file, or environment variable
+// GetRedirectURL returns the redirect url to be passed to Auth as set via default, config file, or environment variable.
```
Comment (hferentschik) [inline internal/configuration/env_config.go]: :-) Nice to see that you take care of punctuation as well

File: internal/storage/store.go [hunk 5]
```diff
@@ -1,22 +1,26 @@
...
 )
 
 var storeLogger = log.WithFields(log.Fields{"component": "store"})
 
+// Store includes all methods required to interact with the database
 type Store interface {
 	CreateRequest(r *Request) error
 	GetRequests(ns string) (result []Request, err error)
-	IncRequestRetry(r *Request) (errs []error)
+	IncreaseRequestRetry(r *Request) (errs []error)
```
Comment (hferentschik) [inline internal/storage/store.go]: I don't think that "Increase" == "Inc"
Inc stand for increment which is different from increasing something. So either 'Inc' which might be common enough, or 'Incremement'

File: internal/storage/store_test.go [hunk 6]
```diff
@@ -25,7 +26,7 @@ func (m *mockStore) GetRequests(ns string) (result []Request, err error) {
 	return nil, nil
 }
 
-func (m *mockStore) IncRequestRetry(r *Request) (errs []error) {
+func (m *mockStore) IncreaseRequestRetry(r *Request) (errs []error) {
```
Comment (hferentschik) [inline internal/storage/store_test.go]: -1 Not  'Increase'

**Comment by hferentschik** [comment]
> I would need help with what is remaining.

What specifically do you need? Some of the outstanding issues seem straight forward, like 'mockedProxyApi should be mockedProxyAPI', right? Or am I missing something.

_GHHeader_ is how we determine whether we are dealing with a GitHub webhook. Look at a GitHub webhook and what is send (check your webhook config for your test openshift.io account (assuming you have one)). We look at the header to make sure we are dealing with a GitHub webhook. If not, we discard the request.

**Comment by hferentschik** [comment]
I did a quick review and added some comments. Basically on track and just needs completion. I want to finish the Proxy side of multi-cluster first now, so additional reviews might take some time. Just keep pushing to the pull request and if you want to make sure I see it, send me a quick ping as well. I try to respond as fast as possible.

File: internal/configuration/env_config.go (hunk 4 above)
Comment (kishansagathiya) [reply internal/configuration/env_config.go]: This is mostly to keep you happy ;) 
Otherwise, all of my comments end without full stop

File: internal/storage/store.go (hunk 5 above)
Comment (kishansagathiya) [reply internal/storage/store.go]: I would change this to IncrementRequestRetry()

File: internal/storage/store_test.go (hunk 6 above)
Comment (kishansagathiya) [reply internal/storage/store_test.go]: Same as above

**Comment by kishansagathiya** [comment]
> 'mockedProxyApi should be mockedProxyAPI', right? Or am I missing something.

Seems like something I would have missed while rebasing and resolving conflicts. So you can ignore this one.

GetGHData, OpenShiftIdle and OpenShiftDataRoute are something that I don't understand.

Token, Result and TokenResult are related to https://github.com/fabric8-services/fabric8-jenkins-proxy/issues/190

**Comment by kishansagathiya** [comment]
> Doubt: main.go createAPIRouter() creates proxy API and router for it. What does createProxyRouter do then?

?

**Comment by hferentschik** [comment]
> Doubt: main.go createAPIRouter() creates proxy API and router for it. What does createProxyRouter do then?

`createProxyRouter` is a bad name. If you look at the code, it does not even return a router, but http.ServeMux. As you say _createAPIRouter()_ is creating a router for the REST API of the Proxy. createProxyRouter is the HTTP server handler which handles the incoming webhook and UI requests. I guess technically this could be rolled in one, but then it would not be just "createAPIRouter", but more _createRouter_.

**Comment by kishansagathiya** [comment]
Note that changes done as part of this PR resolves https://github.com/fabric8-services/fabric8-jenkins-proxy/issues/182 as well

**Comment by hferentschik** [comment]
> Note that changes done as part of this PR resolves #182 and #190 as well

+1 works for me. Please note it in the commit body

**Comment by kishansagathiya** [comment]
Will resolve conflicts and push again

File: Makefile [hunk 7]
```diff
@@ -26,8 +26,10 @@ __check_defined = \
     $(if $(value $1),, \
       $(error Undefined $1$(if $2, ($2))))
 
-all: tools build test fmtcheck vet validate_commits image ## Compiles fabric8-jenkins-proxy and runs format and style checks
+.PHONY: all
+all: tools build test fmtcheck vet lint validate_commits image ## Compiles fabric8-jenkins-proxy and runs format and style checks
 
+.PHONY: build
```
Comment (hferentschik) [inline Makefile]: I don't think this is correct. why do you think this should be phony?

File: Makefile [hunk 8]
```diff
@@ -40,9 +42,11 @@ $(BUILD_DIR):
 $(BUILD_DIR)/fabric8-jenkins-proxy: vendor $(BUILD_DIR) ## Builds the Linux binary for the container image $BUILD_DIR
 	CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build  -ldflags="$(LD_FLAGS)" -o $(BUILD_DIR)/$(REGISTRY_IMAGE) ./cmd/fabric8-jenkins-proxy
 
+.PHONY: image
```
Comment (hferentschik) [inline Makefile]: -1 this is definitely not phony

File: Makefile [hunk 9]
```diff
@@ -51,6 +55,7 @@ push: image ## Pushes the container image to the registry
 	docker tag $(REGISTRY_URL):latest $(REGISTRY_URL):$(IMAGE_TAG)
 	docker push $(REGISTRY_URL):$(IMAGE_TAG)
 
+.PHONY: tools
```
Comment (hferentschik) [inline Makefile]: -1, I don't think is phony either

File: cmd/fabric8-jenkins-proxy/main.go [hunk 10]
```diff
@@ -207,6 +207,7 @@ func startWorkers(wg *sync.WaitGroup, ctx context.Context, cancel context.Cancel
 	}
 }
 
+// createProxyRouter is the HTTP server handler which handles the incoming webhook and UI requests.
```
Comment (hferentschik) [inline cmd/fabric8-jenkins-proxy/main.go]: +1

File: internal/configuration/env_config.go [hunk 11]
```diff
@@ -53,41 +54,42 @@ func init() {
 	settings["GetDebugMode"] = Setting{"JC_DEBUG_MODE", defaultDebugMode, []func(interface{}, string) error{util.IsBool}}
 }
 
+// Setting is an element in the proxy configuration. Many of such Setting constitutes full configuration.
```
Comment (hferentschik) [inline internal/configuration/env_config.go]: " Setting is an element in the proxy configuration. It contains the environment variable from which the setting is retrieved, its default value as well as a list of validations which the value of this setting needs to pass."

File: internal/configuration/env_config.go [hunk 12]
```diff
@@ -53,41 +54,42 @@ func init() {
...
 type Setting struct {
 	key          string
 	defaultValue string
 	validations  []func(interface{}, string) error
 }
 
-// EnvConfig reads the configuration from the environment
+// EnvConfig reads the configuration from the environment.
```
Comment (hferentschik) [inline internal/configuration/env_config.go]: "EnvConfig is a Configuration implementation which reads the configuration from the process environment."

File: internal/proxy/proxy.go [hunk 13]
```diff
@@ -29,11 +29,16 @@ import (
 )
 
 const (
-	GHHeader           = "User-Agent"
-	GHAgent            = "GitHub-Hookshot"
+	// GHHeader is how we determine whether we are dealing with a GitHub webhook
+	GHHeader = "User-Agent"
+	// GHAgent is the prefix of the GHHeader
+	GHAgent = "GitHub-Hookshot"
+	// CookieJenkinsIdled is name of the cookie through which we can check if service is idled
```
Comment (hferentschik) [inline internal/proxy/proxy.go]: This is not quite correct. I need to look at the code first, but this description is misleading.

File: internal/proxy/proxy.go [hunk 14]
```diff
@@ -29,11 +29,16 @@ import (
...
 	CookieJenkinsIdled = "JenkinsIdled"
-	ServiceName        = "jenkins"
-	SessionCookie      = "JSESSIONID"
+	// ServiceName is name of service that we are trying to idle or unidle
+	ServiceName = "jenkins"
+	// SessionCookie is name of the session cookie of the service in question
```
Comment (hferentschik) [inline internal/proxy/proxy.go]: That's plain wrong. See comment above.

File: internal/proxy/proxy.go [hunk 15]
```diff
@@ -702,7 +710,7 @@ func (p *Proxy) ProcessBuffer() {
 							resp, err := client.Do(req)
 							if err != nil {
 								log.Error("Error: ", err)
-								errs := p.storageService.IncRequestRetry(&r)
+								errs := p.storageService.IncrementRequestRetry(&r)
```
Comment (hferentschik) [inline internal/proxy/proxy.go]: ok

File: internal/proxy/proxy_cache.go [hunk 16]
```diff
@@ -1,14 +1,16 @@
 package proxy
 
-type ProxyCacheItem struct {
+// CacheItem represents a cache item  consisting of cluster url, namespace, route, scheme(http, https etc).
```
Comment (hferentschik) [inline internal/proxy/proxy_cache.go]: URL, HTTP, HTTPS

File: internal/storage/request.go [hunk 17]
```diff
@@ -3,17 +3,20 @@ package storage
 import (
 	"bytes"
 	"encoding/json"
-	uuid "github.com/satori/go.uuid"
 	"io"
 	"io/ioutil"
 	"net/http"
 	"net/url"
+
+	uuid "github.com/satori/go.uuid"
```
Comment (hferentschik) [inline internal/storage/request.go]: Is this something you IDE does or something golint really requires? I mean the re-odering of the imports?

File: internal/storage/request.go [hunk 18]
```diff
@@ -45,20 +49,24 @@ func NewRequest(r *http.Request, ns string, body []byte) (*Request, error) {
 	}, nil
 }
 
+// TableName for current request.
 func (m Request) TableName() string {
 	return "requests"
 }
 
+// GetHeaders gets headers of the current request.
```
Comment (hferentschik) [inline internal/storage/request.go]: "current" == "this"

File: internal/storage/request.go [hunk 19]
```diff
@@ -45,20 +49,24 @@ func NewRequest(r *http.Request, ns string, body []byte) (*Request, error) {
...
 	err = json.Unmarshal(m.Headers, &result)
 	return
 }
 
+// GetPayloadReader returns an io reader for the request payload.
 func (m Request) GetPayloadReader() io.ReadCloser {
 	return ioutil.NopCloser(bytes.NewReader(m.Payload))
 }
 
+// GetHTTPRequest wraps an *http.Request from current request.
```
Comment (hferentschik) [inline internal/storage/request.go]: "current" == "this" 

Current != this

File: internal/util/multi_error.go [hunk 20]
```diff
@@ -5,20 +5,25 @@ import (
 	"strings"
 )
 
+// MultiError is a list of error.
```
Comment (hferentschik) [inline internal/util/multi_error.go]: "MultiError is a collection of errors"

List is an implementation detail which is not exposed

File: Makefile (hunk 7 above)
Comment (kishansagathiya) [reply Makefile]: I am under an impression that 
Makefile targets are by default file targets. And if we are not using file targets we should use .PHONY
So here we don't have a file called build, thus .PHONY
Is that correct?

File: internal/storage/request.go (hunk 17 above)
Comment (kishansagathiya) [reply internal/storage/request.go]: I think goimports does the grouping
http://goinbigdata.com/goimports-vs-gofmt/

Comment (hferentschik) [reply internal/storage/request.go]: ok, fair enough. I was just wondering. So it is really your IDE, not the linting.

**Comment by hferentschik** [comment]
Merged, thanks
