### PR TITLE
Issue #321 Check if Session cookie is Valid

### LINKED ISSUE #321: Proxy fails to invalidate old cookies when environment is reset
Steps:
- log into https://jenkins.openshift.io
- reset enviroment
- access https://jenkins.openshift.io again 

Expected: 
- should ask user to relogin and then set a new jsessionid 

Actual: 
- Gets too many redirects. 

This happens because the internal cache does not reflect the fact that jenkins was reset and the old jessionid won't work anymore.

### PR DESCRIPTION
**Pull request by kishansagathiya**
Currently, if session cookie is invalid, proxy does not check its
validity and passes the request to Jenkins considering that user is
logged in. Jenkins finds that cookie is not valid, but it can't expire
that cookie since it was setup by proxy. It will try to relogin user by
redirecting which will pass directly to jenkins again since session
cookie exists. And thus we are in a loop, leading to too many redirect
situation.

In proxy, check if cookie is valid. If it is not expire the cookie and
clear relevant cache. This will ask user to relogin without directly
passing the request to jenkins.

Fixes #321 and #336

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @kishansagathiya for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/fabric8-services/fabric8-jenkins-proxy/blob/7239e2052c8bcaa75585324d4d29c78c987ea880/.ike-prow/test-keeper.yaml).

**Comment by kishansagathiya** [comment]
Testing flow for this.
1. Get cookie from browser(https://localhost:8080). Try
```
curl -v --cookie "JSESSIONID.random=$COOKIE_VALUE" https://localhost:8080 --insecure
```
responds with Jenkins homepage
2. Reset environment. Create a quickstart project. Wait for jenkins to be ready fully. Try the same curl we tried earlier.
proxy logs should show something like this
```
{"cluster":"https://api.starter-us-east-2a.openshift.com/","cookie":"JSESSIONID.37d9dde8","level":"info","msg":"cookie: \"JSESSIONID.xyz\" is in cache","ns":"ksagathi-preview-jenkins","time":"2018-10-24T14:03:10+05:30"}
{"cluster":"https://api.starter-us-east-2a.openshift.com/","cookie":"JSESSIONID.xyz","cookietype":"session","level":"info","msg":"Cache has Jenkins route \"jenkins-ksagathi-preview-jenkins.b542.starter-us-east-2a.openshiftapps.com\" in \"$COOKIE_VALUE\"","ns":"ksagathi-preview-jenkins","time":"2018-10-24T14:03:10+05:30"}
{"cluster":"https://api.starter-us-east-2a.openshift.com/","cookie":"JSESSIONID.xyz","cookietype":"session","level":"info","msg":"cookie JSESSIONID.xyz is OLD; expiring the cookie and clear it from cache","ns":"ksagathi-preview-jenkins","time":"2018-10-24T14:03:11+05:30"}
{"component":"proxy","level":"info","msg":"Could not find cache, redirecting to re-login","ns":"ksagathi-preview-jenkins","request-hash":275579967,"time":"2018-10-24T14:03:11+05:30"}
``` 

Thus getting us out of too many redirects

**Comment by kishansagathiya** [comment]
[test]

**Comment by kishansagathiya** [comment]
[ test ]

File: internal/proxy/ui_requests.go [hunk 1]
```diff
@@ -157,6 +157,24 @@ func (p *Proxy) handleJenkinsUIRequest(w http.ResponseWriter, r *http.Request, l
 				scLogger := nsLogger.WithField("cookietype", "session")
 				scLogger.Infof("Cache has Jenkins route %q in %q", pci.Route, cookie.Value)
 
+				isSessionCookieValid, err := checkIfSessionCookieIsValid(pci, cookie)
```
Comment (sthaha) [inline internal/proxy/ui_requests.go]: a better name may be `validSession, err := validateSession(pci, cookie)`

File: internal/proxy/ui_requests.go [hunk 2]
```diff
@@ -157,6 +157,24 @@ func (p *Proxy) handleJenkinsUIRequest(w http.ResponseWriter, r *http.Request, l
...
+				if err != nil {
```
Comment (sthaha) [inline internal/proxy/ui_requests.go]: if there is an internal error when validating cookie, why not redirect to auth?

File: internal/proxy/ui_requests.go [hunk 3]
```diff
@@ -359,3 +377,29 @@ func (p *Proxy) startJenkins(ns, clusterURL string) (state clients.PodState, cod
...
 	return state, code, nil
 }
+
+func checkIfSessionCookieIsValid(pci CacheItem, cookie *http.Cookie) (bool, error) {
+	jenkinsURL := fmt.Sprintf("%s://%s", pci.Scheme, pci.Route)
+
+	req, _ := http.NewRequest("GET", jenkinsURL, nil)
+	req.AddCookie(cookie)
+
+	c := http.DefaultClient
```
Comment (sthaha) [inline internal/proxy/ui_requests.go]: do not use the default client rather, use the client in utils which sets a timeout

**Comment by kishansagathiya** [comment]
On opening Jenkins UI after reset environment you should see logs like these, which indicates that we found 403 with old cookie, we logged in again and got a new cookie and cache
```
{"component":"proxy","header":"-H Accept-Encoding: gzip, deflate, br -H Accept-Language: en-US,en;q=0.9 -H Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8 -H Cookie: screenResolution=1920x1080; JSESSIONID.a1c33f7c=node0$RANDOM3.node0; $RANDOM=$RANDOM2 -H Upgrade-Insecure-Requests: 1 -H User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36","level":"info","msg":"Handling incoming proxy request.","request":"GET /","request-hash":98329953,"time":"2018-10-29T12:39:03+05:30","type":"Jenkins UI"}
{"component":"proxy","level":"info","msg":"Incoming request: / Cookies: [screenResolution JSESSIONID.a1c33f7c $RANDOM] ","request-hash":98329953,"time":"2018-10-29T12:39:03+05:30"}
{"cluster":"https://api.starter-us-east-2a.openshift.com/","cookie":"JSESSIONID.a1c33f7c","level":"info","msg":"cookie: \"JSESSIONID.a1c33f7c\" is in cache","ns":"ksagathi-preview-jenkins","time":"2018-10-29T12:39:03+05:30"}
{"cluster":"https://api.starter-us-east-2a.openshift.com/","cookie":"JSESSIONID.a1c33f7c","cookietype":"session","level":"info","msg":"Cache has Jenkins route \"jenkins-ksagathi-preview-jenkins.b542.starter-us-east-2a.openshiftapps.com\" in \"node0$RANDOM3.node0\"","ns":"ksagathi-preview-jenkins","time":"2018-10-29T12:39:03+05:30"}
{"cluster":"https://api.starter-us-east-2a.openshift.com/","level":"info","msg":"state : \"running\"","ns":"ksagathi-preview-jenkins","time":"2018-10-29T12:39:04+05:30"}
{"cluster":"https://api.starter-us-east-2a.openshift.com/","cookie":"JSESSIONID.a1c33f7c","cookietype":"session","level":"info","msg":"jenkins is running | so rev proxy: {ClusterURL:https://api.starter-us-east-2a.openshift.com/ NS:ksagathi-preview-jenkins Route:jenkins-ksagathi-preview-jenkins.b542.starter-us-east-2a.openshiftapps.com Scheme:https}","ns":"ksagathi-preview-jenkins","time":"2018-10-29T12:39:04+05:30"}
{"component":"proxy","level":"info","msg":"returned: |key: \"node0$RANDOM3.node0\" |ns: \"ksagathi-preview-jenkins\" |fwd: true|","request-hash":98329953,"time":"2018-10-29T12:39:04+05:30"}
{"component":"proxy","is_valid_session":true,"level":"info","msg":"Write Header called with 403","redirect_url":"/","request-hash":98329953,"request_url":"https://jenkins-ksagathi-preview-jenkins.b542.starter-us-east-2a.openshiftapps.com/","response_recorder":"true","response_timeout":25000000000,"time":"2018-10-29T12:39:05+05:30"}
{"component":"proxy","is_valid_session":true,"level":"info","msg":"WriteHeader 403 - OK","redirect_url":"/","request-hash":98329953,"request_url":"https://jenkins-ksagathi-preview-jenkins.b542.starter-us-east-2a.openshiftapps.com/","response_recorder":"true","response_timeout":25000000000,"time":"2018-10-29T12:39:05+05:30"}
{"component":"proxy","is_valid_session":true,"level":"info","msg":"Write stuff len: 837 - OK","redirect_url":"/","request-hash":98329953,"request_url":"https://jenkins-ksagathi-preview-jenkins.b542.starter-us-east-2a.openshiftapps.com/","response_recorder":"true","response_timeout":25000000000,"time":"2018-10-29T12:39:05+05:30"}
{"component":"proxy","level":"info","msg":"clearing cache for namespace: ksagathi-preview-jenkins, cache_key: node0$RANDOM3.node0","time":"2018-10-29T12:39:05+05:30"}
{"component":"proxy","level":"info","msg":"cookie is OLD; expiring the cookie, cookie_name: JSESSIONID.a1c33f7c, namespace: ksagathi-preview-jenkins","time":"2018-10-29T12:39:05+05:30"}
{"component":"proxy","header":"-H Accept-Encoding: gzip, deflate, br -H Accept-Language: en-US,en;q=0.9 -H Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8 -H Cookie: screenResolution=1920x1080; JSESSIONID.a1c33f7c=node0$RANDOM3.node0; $RANDOM=$RANDOM2 -H Upgrade-Insecure-Requests: 1 -H User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36","level":"info","msg":"Handling incoming proxy request.","request":"GET /","request-hash":1405529907,"time":"2018-10-29T12:39:05+05:30","type":"Jenkins UI"}
{"component":"proxy","level":"info","msg":"Incoming request: / Cookies: [screenResolution JSESSIONID.a1c33f7c $RANDOM] ","request-hash":1405529907,"time":"2018-10-29T12:39:05+05:30"}
{"component":"proxy","level":"info","msg":"cookies: \"JSESSIONID.a1c33f7c\" is session or idle is OLD; expiring","part":"cookie","request-hash":1405529907,"time":"2018-10-29T12:39:05+05:30"}
{"component":"proxy","level":"info","msg":"Could not find cache, redirecting to re-login","ns":"","request-hash":1405529907,"time":"2018-10-29T12:39:05+05:30"}
{"component":"proxy","level":"info","msg":"Redirecting to auth: \"https://auth.prod-preview.openshift.io/api/login?redirect=https:%2F%2Flocalhost:8080%2F\"","request-hash":1405529907,"time":"2018-10-29T12:39:05+05:30"}
```

File: internal/proxy/cookies/cookies.go [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+	return c.Name == CookieJenkinsIdled
+}
+
+// IsSessionOrIdledCookie return true if given cookie was either set to manage jenkins session
+// or to tell if jenkins is running or not
+func IsSessionOrIdledCookie(c *http.Cookie) bool {
+	return IsSessionCookie(c) || IsIdledCookie(c)
+}
+
+func anyCookie(_ *http.Cookie) bool {
```
Comment (golangcibot) [inline internal/proxy/cookies/cookies.go]: `anyCookie` is unused

File: internal/proxy/cookies/cookies.go [hunk 5]
```diff
@@ -0,0 +1,83 @@
...
+	var jsessionCookie *http.Cookie
+
+	for _, cookie := range cookies {
+		http.SetCookie(w, cookie)
+		if IsSessionCookie(cookie) {
+			jsessionCookie = cookie
+		}
+	}
+	return jsessionCookie
+}
```
Comment (kishansagathiya) [inline internal/proxy/cookies/cookies.go]: Created a new package to avoid import cycles. Except removing anyCookie and exporting methods everything is same.

File: internal/proxy/proxy.go [hunk 6]
```diff
@@ -146,13 +147,19 @@ func (p *Proxy) Handle(w http.ResponseWriter, r *http.Request) {
...
-		ResponseTimeout: p.responseTimeout,
-		Logger:          logEntryWithHash,
-	}
+	rp := reverseproxy.NewReverseProxy(
+		actualURL,
+		p.responseTimeout,
+		okToForward,
+
+		logEntryWithHash,
+	)
```
Comment (kishansagathiya) [inline internal/proxy/proxy.go]: A cosmetic change by creating NewReverseProxy function

File: internal/proxy/proxy.go [hunk 7]
```diff
@@ -222,3 +229,27 @@ func (p *Proxy) constructRoute(clusterURL string, ns string) (string, string, er
...
+			if ok {
+				pci = cacheVal.(CacheItem)
+				p.ProxyCache.Delete(cacheKey)
+
+				proxyLogger.Infof("clearing cache for namespace: %s, cache_key: %s", pci.NS, cacheKey)
+			}
+
+			cookiesutil.ExpireCookie(w, cookie)
+			proxyLogger.Infof("cookie is OLD; expiring the cookie, cookie_name: %s, namespace: %s", cookie.Name, pci.NS)
+
```
Comment (kishansagathiya) [inline internal/proxy/proxy.go]: Whether cache is there or not we have to get rid off this old cookie

File: internal/proxy/reverseproxy/reverseproxy.go [hunk 8]
```diff
@@ -50,4 +68,50 @@ func (rp *ReverseProxy) ServeHTTP(rw http.ResponseWriter, req *http.Request) {
 		logger.Warnf("Error %q - code: %d", rr.err, rr.statusCode)
 		http.Redirect(rw, req, rp.RedirectURL.String(), http.StatusFound)
 	}
+
+	if rr.statusCode == http.StatusForbidden {
```
Comment (kishansagathiya) [inline internal/proxy/reverseproxy/reverseproxy.go]: If not logged in jenkins sets status code as `Forbidden`, have not seen other 4xx status for far.

File: internal/proxy/reverseproxy/reverseproxy.go [hunk 9]
```diff
@@ -50,4 +68,50 @@ func (rp *ReverseProxy) ServeHTTP(rw http.ResponseWriter, req *http.Request) {
...
+		var err error
+		rp.IsValidSession, err = checkSessionValidity(req)
```
Comment (kishansagathiya) [inline internal/proxy/reverseproxy/reverseproxy.go]: we can declare `rp.IsValidSession` so declaring error seperately

File: internal/proxy/reverseproxy/reverseproxy.go [hunk 10]
```diff
@@ -50,4 +68,50 @@ func (rp *ReverseProxy) ServeHTTP(rw http.ResponseWriter, req *http.Request) {
...
+		if err != nil {
+			logger.Error(err)
+		}
+		http.Redirect(rw, req, rp.RedirectURL.String(), http.StatusFound)
```
Comment (kishansagathiya) [inline internal/proxy/reverseproxy/reverseproxy.go]: redirect back to the same URL to which request was made

File: internal/proxy/reverseproxy/reverseproxy.go [hunk 11]
```diff
@@ -50,4 +68,50 @@ func (rp *ReverseProxy) ServeHTTP(rw http.ResponseWriter, req *http.Request) {
...
+			if err != nil {
+				return false, err
+			}
+			defer resp.Body.Close()
+
+			switch resp.StatusCode {
+			case http.StatusOK:
+				return true, err
+			case http.StatusUnauthorized:
+				return false, err
```
Comment (kishansagathiya) [inline internal/proxy/reverseproxy/reverseproxy.go]: I should get rid off this unnecessary status check, since we know that the status returned would be Forbidden if not logged in.

File: internal/proxy/ui_requests.go [hunk 12]
```diff
@@ -264,7 +265,7 @@ func (p *Proxy) handleJenkinsUIRequest(w http.ResponseWriter, r *http.Request, l
 		logger.Infof("Redirecting to auth: %q", redirAuth)
 
 		// clear session and idle cookies as this is a fresh start
-		expireCookiesMatching(w, r, isSessionOrIdledCookie)
+		cookiesutil.ExpireCookiesMatching(w, r, cookiesutil.IsSessionOrIdledCookie)
```
Comment (kishansagathiya) [inline internal/proxy/ui_requests.go]: Changes made only because of cookies.go moved to a different package

File: internal/proxy/reverseproxy/reverseproxy.go (hunk 8 above)
Comment (kishansagathiya) [reply internal/proxy/reverseproxy/reverseproxy.go]: probably a good idea to check for any 4xx status

Comment (kishansagathiya) [reply internal/proxy/reverseproxy/reverseproxy.go]: like 
```suggestion
	if rr.statusCode >= 400 && rr.statusCode < 500 {
```

**Comment by kishansagathiya** [comment]
>that and we really need some tests for ui_requests

@chmouel @sthaha 
Let's do that as a part of a different issue, probably #336. That issue would require changes and discussion much different than what is required for this one.

File: internal/proxy/github.go [hunk 13]
```diff
@@ -60,6 +58,13 @@ func (p *Proxy) handleGitHubRequest(w http.ResponseWriter, r *http.Request, requ
 	ns = namespace.Name
 	clusterURL := namespace.ClusterURL
 	nsLogger := requestLogEntry.WithField("ns", ns)
+
+	jenkins, _, err := GetJenkins(nil, p.idler, p.tenant, "", requestLogEntry)
```
Comment (golangcibot) [inline internal/proxy/github.go]: ineffectual assignment to `err`

File: internal/proxy/github.go [hunk 14]
```diff
@@ -144,9 +149,14 @@ func (p *Proxy) ProcessBuffer() {
 
 					nsLogger.WithFields(log.Fields{"repository": gh.Repository.CloneURL}).Info("Retrying request")
 					namespace, err := p.getUserWithRetry(gh.Repository.CloneURL, proxyLogger, defaultRetry)
-					clusterURL := namespace.ClusterURL
 
-					state, err := p.idler.State(ns, clusterURL)
+					jenkins, _, err := GetJenkins(nil, p.idler, p.tenant, "", nsLogger)
```
Comment (golangcibot) [inline internal/proxy/github.go]: ineffectual assignment to `err`

**Comment by kishansagathiya** [comment]
Tests for reverseproxy are done. Let me know if you have any thoughts.

File: internal/proxy/reverseproxy/reverseproxy.go [hunk 15]
```diff
@@ -48,6 +65,48 @@ func (rp *ReverseProxy) ServeHTTP(rw http.ResponseWriter, req *http.Request) {
...
 	}
 }
+
+func checkSessionValidity(req *http.Request) (bool, error) {
+	requestURL := req.URL
+	cookies := req.Cookies()
+
+	jenkinsURL := fmt.Sprintf("%s://%s", requestURL.Scheme, requestURL.Host)
+
+	for _, cookie := range cookies {
```
Comment (hrishin) [inline internal/proxy/reverseproxy/reverseproxy.go]: What is expected behavior if cookies contain more than 1 `sessions cookies`. ?

1) It should go through all session cookies and evaluate it's valid or not. If it found a valid one then it should continue the redirection normal redirection flow? 
If yes then this code would need to be fixed. At this moment it would evaluate to `false` even though cookies contains valid session.

File: internal/auth/auth.go [hunk 16]
```diff
@@ -36,16 +43,31 @@ type TokenJSON struct {
...
+	KID string `json:"kid"`
+	Key string `json:"key"`
+}
+
+// KeyList is a list of cryptographics keys used for authentication and authorization
+type KeyList struct {
+	Keys []Key `json:"keys"`
+}
+
+var defaultClient Service
```
[the remark this answers is not in the document]
Comment (kishansagathiya) [reply internal/auth/auth.go]: It is of Service type, but what would be stored here would be a client.

File: internal/proxy/jenkins.go [hunk 17]
```diff
@@ -0,0 +1,150 @@
...
+}
+
+// State returns state of Jenkins associated with given namespace
+func (j *Jenkins) State() (clients.PodState, error) {
+	return j.idler.State(j.info.NS, j.info.ClusterURL)
+}
+
+// Start unidles Jenkins only if it is idled and returns the
+// state of the pod, the http status of calling unidle, and error if any
+func (j *Jenkins) Start() (state clients.PodState, code int, err error) {
```
[the remark this answers is not in the document]
Comment (kishansagathiya) [reply internal/proxy/jenkins.go]: Start method is not just used for starting Jenkins, but also for knowing the pod state. If Jenkins is up we can stop calling start again and again.

File: internal/proxy/reverseproxy/reverseproxy.go (hunk 15 above)
Comment (kishansagathiya) [reply internal/proxy/reverseproxy/reverseproxy.go]: We have code that makes sure that we don't end up in a situation where we have two session cokkies.
https://github.com/fabric8-services/fabric8-jenkins-proxy/blob/b065e0b31d87219e076df01da1f0ff1d9b32b212/internal/proxy/ui_requests.go#L102

File: cmd/fabric8-jenkins-proxy/main.go [hunk 18]
```diff
@@ -99,11 +99,11 @@ func main() {
 	}
 	mainLogger.WithField("clusters", clusters).Info("Retrieved cluster view")
 
-	start(config, &tenant, wit, idler, store, clusters)
+	start(config, idler, &tenant, wit, store, clusters)
 }
 
-func start(config configuration.Configuration, tenant *clients.Tenant, wit clients.WIT, idler clients.IdlerService, store storage.Store, clusters map[string]string) {
-	proxy, err := proxy.NewProxy(tenant, wit, idler, store, config, clusters)
+func start(config configuration.Configuration, idler clients.IdlerService, tenant clients.TenantService, wit clients.WIT, store storage.Store, clusters map[string]string) {
```
[the remark this answers is not in the document]
Comment (kishansagathiya) [reply cmd/fabric8-jenkins-proxy/main.go]: good idea

**Comment by kishansagathiya** [comment]
I found few problem with the code(login with cookies). I am working on those.

File: internal/proxy/reverseproxy/reverseproxy.go [hunk 19]
```diff
@@ -48,6 +65,48 @@ func (rp *ReverseProxy) ServeHTTP(rw http.ResponseWriter, req *http.Request) {
...
+		if cookiesutil.IsSessionCookie(cookie) {
+
+			r, _ := http.NewRequest("GET", jenkinsURL, nil)
+			r.AddCookie(cookie)
+
+			c := http.DefaultClient
+			resp, err := c.Do(r)
```
[the remark this answers is not in the document]
Comment (kishansagathiya) [reply internal/proxy/reverseproxy/reverseproxy.go]: :+1:

File: internal/proxy/github.go [hunk 20]
```diff
@@ -144,9 +152,14 @@ func (p *Proxy) ProcessBuffer() {
...
 					nsLogger.WithFields(log.Fields{"repository": gh.Repository.CloneURL}).Info("Retrying request")
 					namespace, err := p.getUserWithRetry(gh.Repository.CloneURL, proxyLogger, defaultRetry)
-					clusterURL := namespace.ClusterURL
+					pci := CacheItem{
+						NS:         namespace.Name,
+						ClusterURL: namespace.ClusterURL,
+					}
 
-					state, err := p.idler.State(ns, clusterURL)
+					jenkins, _, err := GetJenkins(p.clusters, &pci, p.idler, p.tenant, "", nsLogger)
```
Comment (golangcibot) [inline internal/proxy/github.go]: ineffectual assignment to `err`

File: internal/clients/tenant.go [hunk 21]
```diff
@@ -140,19 +140,23 @@ func GetNamespaceByType(ti TenantInfo, typ string) (r Namespace, err error) {
...
 	ti, err := t.GetTenantInfo(uid)
 	if err != nil {
-		return
+		return Namespace{}, err
 	}
 
 	namespace, err = GetNamespaceByType(ti, "jenkins")
 	if err != nil {
-		return
+		return Namespace{}, err
```
[the remark this answers is not in the document]
Comment (kishansagathiya) [reply internal/clients/tenant.go]: True, but this way we know what we are returning, which is why whenever I find I convert naked returns to something like this

[the remark this answers is not in the document]
Comment (khrm) [reply internal/clients/tenant.go]: I meant 
`return namespace, err` not naked return

**Comment by kishansagathiya** [comment]
Few modifications required in reverse proxy tests, on it

File: cmd/fabric8-jenkins-proxy/main.go (hunk 18 above)
[the remark this answers is not in the document]
Comment (sthaha) [reply cmd/fabric8-jenkins-proxy/main.go]: @hrishin `client.FooService` sounds like an oxymoron to me. it is either `foo.Client` and `foo.Service` or `client.Foo` not `client.FooService`

File: internal/proxy/reverseproxy/reverseproxy.go (hunk 19 above)
[the remark this answers is not in the document]
Comment (sthaha) [reply internal/proxy/reverseproxy/reverseproxy.go]: `utils.HTTPClient` IIRC

File: cmd/fabric8-jenkins-proxy/main.go [hunk 22]
```diff
@@ -99,11 +99,11 @@ func main() {
 	}
 	mainLogger.WithField("clusters", clusters).Info("Retrieved cluster view")
 
-	start(config, &tenant, wit, idler, store, clusters)
+	start(config, idler, &tenant, wit, store, clusters)
 }
 
-func start(config configuration.Configuration, tenant *clients.Tenant, wit clients.WIT, idler clients.IdlerService, store storage.Store, clusters map[string]string) {
-	proxy, err := proxy.NewProxy(tenant, wit, idler, store, config, clusters)
+func start(config configuration.Configuration, idler clients.IdlerService, tenant clients.TenantService, wit clients.WITService, store storage.Store, clusters map[string]string) {
```
Comment (sthaha) [inline cmd/fabric8-jenkins-proxy/main.go]: @hrishin @kishansagathiya  client.Foo was just fine. How is Suffixing Service to every client adding any more clarity than what it had?

File: cmd/fabric8-jenkins-proxy/main.go (hunk 18 above)
[the remark this answers is not in the document]
Comment (kishansagathiya) [reply cmd/fabric8-jenkins-proxy/main.go]: @sthaha It's client**s**

File: cmd/fabric8-jenkins-proxy/main.go (hunk 22 above)
Comment (kishansagathiya) [reply cmd/fabric8-jenkins-proxy/main.go]: Service is suffixed with interface names. 
I went with the flow that we had so far (the package name is `clients`)
I agree that it is an oxymoron. To satisfy the name change you are asking for, we will have to do little rearrangement. I was actually talking about some with @khrm. 

We can have idler, wit, tenant, and auth(why is this kept separate than other clients!) packages inside clients repo. We can get rid of mock as well and move them into respective packages (i.e, mock_idler.go inside `idler` package instead of some `mocks` package)

Comment (khrm) [reply cmd/fabric8-jenkins-proxy/main.go]: Yea. No need for that auth package. On other hand, I too don't like stuttering. So better to use caps for interface and small letter for concrete implementation. Or define interface where you are going to use it. But latter approach would require separate mock package.

**Comment by kishansagathiya** [comment]
Is it harmful trying to expire the same cookie multiple times by having multiple set-cookie header (bunch of such cases in proxy)

**Comment by khrm** [comment]
+1

File: internal/proxy/ui_requests_test.go [hunk 23]
```diff
@@ -1,18 +1,165 @@
...
 
 import (
+	"net/http"
 	"net/http/httptest"
 	"testing"
 
+	"github.com/fabric8-services/fabric8-jenkins-proxy/internal/clients"
+
+	uuid "github.com/satori/go.uuid"
+	gock "gopkg.in/h2non/gock.v1"
```
Comment (kishansagathiya) [inline internal/proxy/ui_requests_test.go]: Add gock to Gopkg.toml
